name: Upload Release

on:
  release:
    types: [released]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Copy File
      run: cp hcinstall.sh hcinstall

    - name: Push scripts
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'hcinstall'
        destination_repo: 'robertpeteuil/iac.sh'
        destination_branch: 'master'
        destination_folder: 'docs'
        user_email: 'actions@github.com'
        user_name: 'release-action'
        commit_message: 'add latest release'
  
